name: NuGet

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd ./DG.Common/DG.Common/
          dotnet pack -c Release -o out -p:GeneratePackageOnBuild=false
        
      - name: Push Package to NuGet.org
        run: dotnet nuget push ./DG.Common/DG.Common/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

